# Generated by Django 6.0.5 on 2026-05-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('document_number', models.CharField(max_length=30, verbose_name='Номер документа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса проживання')),
            ],
            options={
                'verbose_name': 'Заявник',
                'verbose_name_plural': 'Заявники',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва підрозділу')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис послуги')),
                ('processing_days', models.PositiveIntegerField(verbose_name='Термін виконання, днів')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вартість')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='Дата подання')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('waiting', 'Очікує документи'), ('completed', 'Виконана'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус заяви')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.applicant', verbose_name='Заявник')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Працівник')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.department', verbose_name='Підрозділ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Заява',
                'verbose_name_plural': 'Заяви',
            },
        ),
    ]
